export const NO_WALLET_TYPES = {
  generic: {
    urlClose: '/tabs/home',
    urlPage: '/tabs/wallets',
    img: 'assets/img/wallets/no-wallet.svg',
    title: 'wallets.no_wallet.title',
    subtitle: 'wallets.no_wallet.subtitle',
    nameButton: 'wallets.no_wallet.button',
  },
  no_wallet_defi_investments: {
    urlClose: '/tabs/home',
    urlPage: '/wallets/create-first/disclaimer',
    urlLink: '/tabs/wallets',
    img: 'assets/img/wealth_management/no-wallet.svg',
    title: 'wealth_managements.no_wallet.title',
    subtitle: 'wealth_managements.no_wallet.subtitle',
    nameButton: 'wealth_managements.no_wallet.button',
    nameLink: 'wealth_managements.no_wallet.link',
  },
  no_wallet_to_donate: {
    urlClose: '/tabs/home',
    urlPage: '/tabs/wallets',
    urlLink: '/donations/causes',
    img: 'assets/img/wallets/no-wallet.svg',
    title: 'donations.send_donations.no_wallet.title',
    subtitle: 'donations.send_donations.no_wallet.subtitle',
    nameButton: 'donations.send_donations.no_wallet.button',
    nameLink: 'donations.send_donations.no_wallet.link',
  },
};
