export const REMOTE_CONFIG_DEFAULTS = {
  ff_buyCrypto: false,
  ff_updateAppModal: false,
  referralsMenuUrl_referralPromotionCard: 'referrals/closed',
  ff_swap: false,
  ff_homeWalletBackupWarningModal: false,
  ff_educationCardAvailable: false,
  investmentProducts: undefined,
  onOffRampsProviders: undefined,
  ff_newLogin: true,
  newTokensAvailable: undefined,
  ff_newTokenAvailable: false,
  ff_kriptonNewUx: false,
  ff_bioauth: true,
  inReview: true,
  lastVersion: undefined,
  ff_address_list: false,
  ff_experimentOnboarding: false,
  ff_sellEnabled: false,
  ff_fundFaucet: false,
  ff_fundFaucetOnWarranties: false,
  ff_walletConnectV2: false,
  ff_disableGDriveBackup: false,
  ff_warranty_wallet: false,
  minimumWarrantyAmount: undefined
};
