export const DATA = {
  finance: [
    {
      id: 1,
      order: 1,
      icon: 'assets/ux-icons/introduction-finances.svg',
      title: 'financial_education.home.module_finance.module_1.title',
      coming_soon: false,
      category: 1,
      submodules: [
        {
          id: 1,
          order: 1,
          title: 'financial_education.home.module_finance.module_1.sub_modules.sub_module_1.title',
          info: 'financial_education.home.module_finance.module_1.sub_modules.sub_module_1.description',
          img: 'assets/img/financial-education/startied.svg',
          learning_code: 'dVKXJqBs',
          test_code: 'GGLKURh6',
          data_to_track: 'how_to_get_started_in_finance',
          screen_view_label: 'ux_education_screenview_intro_fin_complete',
          module: 1,
          status: 'completed',
        },
        {
          id: 2,
          order: 2,
          title: 'financial_education.home.module_finance.module_1.sub_modules.sub_module_2.title',
          info: 'financial_education.home.module_finance.module_1.sub_modules.sub_module_2.description',
          img: 'assets/img/financial-education/manage-money.svg',
          learning_code: 'FNFBi9Lb',
          test_code: 'PesYFNQ5',
          data_to_track: 'budgets',
          screen_view_label: 'ux_education_screenview_intro_fin_complete',
          module: 1,
          status: 'to_do',
        },
      ],
      status: 'to_do',
    },
    {
      id: 2,
      order: 2,
      icon: 'assets/ux-icons/quote.svg',
      title: 'financial_education.home.module_finance.module_2.title',
      coming_soon: true,
      category: 1,
      submodules: [],
      status: 'to_do',
    },
    {
      id: 3,
      order: 3,
      icon: 'assets/ux-icons/invest.svg',
      title: 'financial_education.home.module_finance.module_3.title',
      coming_soon: true,
      category: 1,
      submodules: [],
      status: 'to_do',
    },
  ],
  crypto: [
    {
      id: 4,
      order: 1,
      icon: 'assets/ux-icons/clip.svg',
      title: 'financial_education.home.module_crypto.module_1.title',
      coming_soon: false,
      category: 2,
      submodules: [
        {
          id: 3,
          order: 1,
          title: 'financial_education.home.module_crypto.module_1.sub_modules.sub_module_1.title',
          info: 'financial_education.home.module_crypto.module_1.sub_modules.sub_module_1.description',
          img: 'assets/img/financial-education/maitenance.svg',
          learning_code: 's9aemiAX',
          test_code: 'fwLYdNnE',
          data_to_track: 'what_is_blockchain',
          screen_view_label: 'ux_education_screenview_intro_block_complete',
          module: 4,
          status: 'to_do',
        },
      ],
      status: 'to_do',
    },
    {
      id: 5,
      order: 2,
      icon: 'assets/ux-icons/money.svg',
      title: 'financial_education.home.module_crypto.module_2.title',
      coming_soon: true,
      category: 2,
      submodules: [],
      status: 'to_do',
    },
    {
      id: 6,
      order: 3,
      icon: 'assets/ux-icons/briefcase.svg',
      title: 'financial_education.home.module_crypto.module_3.title',
      coming_soon: true,
      category: 2,
      submodules: [],
      status: 'to_do',
    },
  ],
};
