import { FiatRampProviderCountry } from '../interfaces/fiat-ramp-provider-country';
export const COUNTRIES: FiatRampProviderCountry[] = [
  { name: 'Mexico', isoCodeAlpha3: 'MEX', iso4217CurrencyCode: 'MXN', value: 'fiat_ramps.countries_list.mexico', directaCode: 'MX',isoCurrencyCodeDirecta: 'MXN', isoCurrencyCodeMoonpay: 'MXN'},
  { name: 'Guatemala', isoCodeAlpha3: 'GTM', iso4217CurrencyCode: 'GTQ',  value: 'fiat_ramps.countries_list.guatemala' },
  { name: 'Honduras', isoCodeAlpha3: 'HND', iso4217CurrencyCode: 'HNL', value: 'fiat_ramps.countries_list.honduras' },
  { name: 'Costa Rica', isoCodeAlpha3: 'CRI', iso4217CurrencyCode: 'CRC', value: 'fiat_ramps.countries_list.costa_rica', fiatCode: 'crc', flagRoute: 'assets/img/countries/costa-rica.svg'},
  { name: 'Colombia', isoCodeAlpha3: 'COL', iso4217CurrencyCode: 'COP', value: 'fiat_ramps.countries_list.colombia', fiatCode: 'cop',  directaCode: 'CO',isoCurrencyCodeDirecta: 'COP', isoCurrencyCodeMoonpay: 'COP', flagRoute: 'assets/img/countries/colombia.svg'},
  { name: 'Argentina', isoCodeAlpha3: 'ARG', iso4217CurrencyCode: 'ARS', value: 'fiat_ramps.countries_list.argentina', fiatCode: 'ars',  directaCode: 'AR', isoCurrencyCodeDirecta: 'ARS', flagRoute:'assets/img/countries/argentina.svg'},
  { name: 'Brasil', isoCodeAlpha3: 'BRA', iso4217CurrencyCode: 'BRL', value: 'fiat_ramps.countries_list.brasil', directaCode: 'BR', isoCurrencyCodeDirecta:'BRL', isoCurrencyCodeMoonpay: 'BRL'},
  { name: 'El Salvador', isoCodeAlpha3: 'SLV', iso4217CurrencyCode: 'USD', value: 'fiat_ramps.countries_list.el_salvador', flagRoute: 'assets/img/countries/el-salvador.svg'},
  { name: 'Guyana', isoCodeAlpha3: 'GUY', iso4217CurrencyCode: 'GYD', value: 'fiat_ramps.countries_list.guyana' },
  { name: 'Paraguay', isoCodeAlpha3: 'PRY', iso4217CurrencyCode: 'PYG', value: 'fiat_ramps.countries_list.paraguay' },
  { name: 'Australia', isoCodeAlpha3: 'AUS', iso4217CurrencyCode: 'AUD', value: 'fiat_ramps.countries_list.australia', isoCurrencyCodeMoonpay: 'AUD' },
  { name: 'Peru', isoCodeAlpha3: 'PER', iso4217CurrencyCode: 'PEN', value: 'fiat_ramps.countries_list.peru', directaCode: 'PE',isoCurrencyCodeDirecta:'PEN', isoCurrencyCodeMoonpay: 'PEN'},
  { name: 'Portugal', isoCodeAlpha3: 'PRT', iso4217CurrencyCode: 'EUR', value: 'fiat_ramps.countries_list.portugal', isoCurrencyCodeMoonpay: 'EUR'},
  { name: 'España', isoCodeAlpha3: 'ESP', iso4217CurrencyCode: 'EUR', value: 'fiat_ramps.countries_list.spain', isoCurrencyCodeMoonpay: 'EUR' },
  { name: 'Uruguay', isoCodeAlpha3: 'URY', iso4217CurrencyCode: 'UYU', value: 'fiat_ramps.countries_list.uruguay',fiatCode: 'uyu', flagRoute: 'assets/img/countries/uruguay.svg' },
  { name: 'Estados Unidos', isoCodeAlpha3: 'USA', iso4217CurrencyCode: 'USD', value: 'fiat_ramps.countries_list.united_states', isoCurrencyCodeMoonpay: 'USD' },
  { name: 'Venezuela', isoCodeAlpha3: 'VEN', iso4217CurrencyCode: 'VEF', value: 'fiat_ramps.countries_list.venezuela', fiatCode: 'ves', flagRoute:'assets/img/countries/venezuela.svg' },
  { name: 'Chile', isoCodeAlpha3: 'CHL', iso4217CurrencyCode: 'CLP', value: 'fiat_ramps.countries_list.chile', directaCode: 'CL', isoCurrencyCodeDirecta:'CLP'},
  { name: 'Ecuador', isoCodeAlpha3: 'ECU', iso4217CurrencyCode: 'USD', value: 'fiat_ramps.countries_list.ecuador', directaCode: 'EC', isoCurrencyCodeDirecta:'USD', isoCurrencyCodeMoonpay: 'USD'},
];
