export const Coins = [
  {
    id: 1,
    name: 'BTC - Bitcoin',
    logoRoute: '../../assets/img/coins/BTC.svg',
    last: false,
    symbol: 'BTC',
  },
  {
    id: 2,
    name: 'USDT - Tether',
    logoRoute: '../../assets/img/coins/USDT.svg',
    last: false,
    symbol: 'USDT',
  },
  {
    id: 3,
    name: 'BNB - Binance',
    logoRoute: '../../assets/img/coins/BNB.svg',
    last: false,
    symbol: 'BNB',
  },
  {
    id: 4,
    name: 'ETH - Ethereum',
    logoRoute: '../../assets/img/coins/ETH.svg',
    last: true,
    symbol: 'ETH',
  },
  {
    id: 5,
    name: 'LTC- Litecoin',
    logoRoute: '../../assets/img/coins/LTC.svg',
    last: true,
    symbol: 'LTC',
  },
  {
    id: 6,
    name: 'DOGE- Dogecoin',
    logoRoute: '../../assets/img/coins/DOGE.svg',
    last: true,
    symbol: 'DOGE',
  },
  {
    id: 7,
    name: 'USDC- USD Coin',
    logoRoute: '../../assets/img/coins/USDC.svg',
    last: true,
    symbol: 'USDC',
  },
  {
    id: 8,
    name: 'PAX- Paxos Standard',
    logoRoute: '../../assets/img/coins/PAX.svg',
    last: true,
    symbol: 'PAX',
  },
];
