import { Coin } from '../interfaces/coin.interface';
import { environment } from 'src/environments/environment';
import aaveAbi from './assets-abi/aave-abi.json';
import linkAbi from './assets-abi/link-abi.json';
import uniAbi from './assets-abi/uni-abi.json';
import usdtAbi from './assets-abi/usdt-abi.json';
import rifAbi from './assets-abi/rif-abi.json';
import sovAbi from './assets-abi/sov-abi.json';

export const NONPROD_COINS: Coin[] = [
  {
    id: 1,
    name: 'ETH - Ethereum',
    logoRoute: 'assets/img/coins/ETH.svg',
    last: false,
    value: 'ETH',
    network: 'ERC20',
    chainId: 42,
    rpc: environment.ethAlchemyApiUrl,
    native: true,
  },
  {
    id: 2,
    name: 'LINK - Chainlink',
    logoRoute: 'assets/img/coins/LINK.png',
    last: false,
    value: 'LINK',
    network: 'ERC20',
    chainId: 42,
    rpc: environment.ethAlchemyApiUrl,
    contract: '0xa36085f69e2889c224210f603d836748e7dc0088',
    abi: linkAbi,
    decimals: 18,
  },
  {
    id: 3,
    name: 'USDT - Tether',
    logoRoute: 'assets/img/coins/USDT.svg',
    last: false,
    value: 'USDT',
    network: 'ERC20',
    chainId: 42,
    rpc: environment.ethAlchemyApiUrl,
    contract: '0x07de306ff27a2b630b1141956844eb1552b956b5',
    abi: usdtAbi,
    decimals: 6,
  },
  {
    id: 4,
    name: 'AAVE',
    logoRoute: 'assets/img/coins/AAVE.svg',
    last: false,
    value: 'AAVE',
    network: 'ERC20',
    chainId: 42,
    rpc: environment.ethAlchemyApiUrl,
    contract: '0xb597cd8d3217ea6477232f9217fa70837ff667af',
    abi: aaveAbi,
    decimals: 18,
  },
  {
    id: 5,
    name: 'UNI - Uniswap',
    logoRoute: 'assets/img/coins/UNI.svg',
    last: true,
    value: 'UNI',
    network: 'ERC20',
    chainId: 42,
    rpc: environment.ethAlchemyApiUrl,
    contract: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
    abi: uniAbi,
    decimals: 18,
  },
  {
    id: 6,
    name: 'RBTC - Smart Bitcoin',
    logoRoute: 'assets/img/coins/RBTC.png',
    last: false,
    value: 'RBTC',
    network: 'RSK',
    chainId: 31,
    rpc: environment.rskApiUrl,
    native: true,
  },
  {
    id: 7,
    name: 'RIF - Rifos',
    logoRoute: 'assets/img/coins/RIF.png',
    last: true,
    value: 'RIF',
    network: 'RSK',
    chainId: 31,
    rpc: environment.rskApiUrl,
    contract: '0x19F64674D8A5B4E652319F5e239eFd3bc969A1fE',
    abi: rifAbi,
    decimals: 18,
  },

  {
    id: 8,
    name: 'MATIC - Polygon',
    logoRoute: 'assets/img/coins/MATIC.png',
    last: false,
    value: 'MATIC',
    network: 'MATIC',
    chainId: 80001,
    rpc: environment.maticApiUrl,
    decimals: 18,
    native: true,
  },
  {
    id: 9,
    name: 'SOV - Sovryn',
    logoRoute: 'assets/img/coins/SOV.png',
    last: true,
    value: 'SOV',
    network: 'RSK',
    chainId: 31,
    rpc: environment.rskApiUrl,
    contract: '0x6a9A07972D07e58F0daf5122d11E069288A375fb',
    abi: sovAbi,
    decimals: 18,
  },
];
