export const CAUSES = [
  {
    id: 'unhcr',
    image: 'assets/img/donations/causes/cause_1/image.jpg',
    title: 'UNHCR',
    logo: 'assets/img/donations/causes/cause_1/logo.svg',
    type: 'humanitary',
    title_1: 'donations.description_cause.info.unhcr.title_1',
    title_2: 'donations.description_cause.info.unhcr.title_2',
    title_3: 'donations.description_cause.info.unhcr.title_3',
    description: 'donations.description_cause.info.unhcr.description',
    social_media: [
      { logo: 'instagram', link: 'https://instagram.com/acnur', text: 'instagram.com/acnur' },
      { logo: 'twitter', link: 'https://twitter.com/ACNURamericas', text: 'twitter.com/ACNURamericas' },
      { logo: 'mail', link: 'https://argbu@unhcr.org', text: 'argbu@unhcr.org' },
    ],
  },
  {
    id: 'freethegirls',
    image: 'assets/img/donations/causes/cause_2/image.jpg',
    title: 'Free the Girls',
    logo: 'assets/img/donations/causes/cause_2/logo.jpg',
    type: 'human_rights',
    title_1: 'donations.description_cause.info.free_the_girls.title_1',
    title_2: 'donations.description_cause.info.free_the_girls.title_2',
    title_3: 'donations.description_cause.info.free_the_girls.title_3',
    description: 'donations.description_cause.info.free_the_girls.description',
    social_media: [
      { logo: 'instagram', link: 'https://instagram.com/freethegirlsbras', text: 'instagram.com/freethegirlsbras' },
      { logo: 'twitter', link: 'https://twitter.com/freethegirls', text: 'twitter.com/freethegirls' },
      { logo: 'mail', link: 'https://info@rainforestrescue.org.au', text: 'info@rainforestrescue.org.au' },
    ],
  },
  {
    id: 'rainforestrescue',
    image: 'assets/img/donations/causes/cause_3/image.jpg',
    title: 'Rainforest rescue',
    logo: 'assets/img/donations/causes/cause_3/logo.svg',
    type: 'environment',
    title_1: 'donations.description_cause.info.rainforest_rescue.title_1',
    title_2: 'donations.description_cause.info.rainforest_rescue.title_2',
    title_3: 'donations.description_cause.info.rainforest_rescue.title_3',
    description: 'donations.description_cause.info.rainforest_rescue.description',
    social_media: [
      { logo: 'instagram', link: 'https://instagram.com/rainforestrescueau', text: 'instagram.com/rainforestrescueau' },
      { logo: 'youtube', link: 'https://youtube.com/Rainforest Rescue', text: 'youtube.com/Rainforest Rescue' },
      { logo: 'mail', link: 'https://info@rainforestrescue.org.au', text: 'info@rainforestrescue.org.au' },
    ],
  },
  {
    id: 'water',
    image: 'assets/img/donations/causes/cause_4/image.jpg',
    title: 'Water.org',
    logo: 'assets/img/donations/causes/cause_4/logo.jpg',
    type: 'humanitary',
    title_1: 'donations.description_cause.info.water.title_1',
    title_2: 'donations.description_cause.info.water.title_2',
    title_3: 'donations.description_cause.info.water.title_3',
    description: 'donations.description_cause.info.water.description',
    social_media: [
      { logo: 'instagram', link: 'https://instagram.com/water', text: 'instagram.com/water' },
      { logo: 'twitter', link: 'https://twitter.com/water', text: 'twitter.com/water' },
      { logo: 'mail', link: 'https://water.org/contact-us', text: 'water.org/contact-us' },
    ],
  },
];
