export const TYC_ITEMS = [
    {
        img:'/assets/img/users/term-and-conditions/logo-xcapit.svg',
        title:'profiles.user_profile_menu.terms_and_conditions.tyc',
        route:'https://www.xcapit.com/terminos-y-condiciones',
        key:'userAcceptedToS',
        isXcapit:true,
    },
    {
        img:'/assets/img/users/term-and-conditions/logo-xcapit.svg',
        title:'profiles.user_profile_menu.terms_and_conditions.privacy_policy',
        route:'https://www.xcapit.com/politicas-de-privacidad',
        key:'userAcceptedToS',
        isXcapit:true,
    },
    {
        img:'/assets/img/users/term-and-conditions/icon-2pi.svg',
        title:'profiles.user_profile_menu.terms_and_conditions.2pi.title',
        route:'https://docs.2pi.network/resources/terms-and-conditions',
        key: '_agreement_2PI_T&C'    
    },
    {
        img:'/assets/img/users/term-and-conditions/icon-1inch.svg',
        title:'profiles.user_profile_menu.terms_and_conditions.inch.title',
        route:'https://docs.1inch.io/docs/aggregation-protocol/api/legal/',
        key:'termsAndConditions1InchSwapAccepted'
    },
    {
        img:'/assets/img/users/term-and-conditions/icon-kripton.svg',
        title:'profiles.user_profile_menu.terms_and_conditions.kripton.title',
        subtitle:'profiles.user_profile_menu.terms_and_conditions.tyc',
        route:'https://kriptonmarket.com/terms-and-conditions',
    },
    {
        img:'/assets/img/users/term-and-conditions/icon-kripton.svg',
        title:'profiles.user_profile_menu.terms_and_conditions.kripton.title',
        subtitle:'profiles.user_profile_menu.terms_and_conditions.privacy_policy',
        route:'https://cash.kriptonmarket.com/privacy',
    },
]