import { RawMenuItem } from '../menu-item/raw-menu-item';

export const RAW_MENU_ITEMS: RawMenuItem[] = [
  {
    position: 1,
    categoryName: 'Help',
    name: 'Faq',
    text: 'profiles.user_profile_menu.faq_help',
    route: '/support/options',
    type: 'link',
    buttonName: 'ux_go_to_faq',
    visible: true,
    newBadge: false,
  },
  {
    position: 2,
    categoryName: 'Help',
    name: 'Support',
    text: 'profiles.user_profile_menu.support_help',
    route: '/tickets/create-support-ticket',
    type: 'link',
    buttonName: 'ux_go_to_contact_support',
    visible: true,
    newBadge: false,
  },
  {
    position: 3,
    categoryName: 'Help',
    name: 'Community',
    text: 'profiles.user_profile_menu.community',
    route: 'https://t.me/xcapit_es',
    type: 'link',
    buttonName: 'ux_community_telegram',
    visible: true,
    newBadge: false,
  },
  {
    position: 4,
    categoryName: 'Help',
    name: 'terms&Conditions',
    text: 'profiles.user_profile_menu.terms_and_conditions.tyc',
    route: '/users/terms-and-conditions',
    type: 'link',
    buttonName: 'ux_go_to_terms_conditions',
    visible: true,
    newBadge: false,
  },
  {
    position: 1,
    categoryName: 'Wallet',
    name: 'SecurityConfiguration',
    text: 'profiles.user_profile_menu.security_configuration',
    route: '/profiles/security-configuration',
    type: 'link',
    buttonName: 'ux_go_to_security_configuration',
    visible: true,
    newBadge: true,
  },
  {
    position: 2,
    categoryName: 'Wallet',
    name: 'RecoveryPhrase',
    text: 'profiles.user_profile_menu.security_phrase',
    route: '/wallets/recovery/info',
    type: 'link',
    buttonName: 'ux_go_to_phrase',
    visible: true,
    newBadge: false,
  },
  {
    position: 3,
    categoryName: 'Wallet',
    name: 'GoogleDriveBackup',
    text: 'profiles.user_profile_menu.google_drive_backup',
    route: '/profiles/backup',
    type: 'link',
    buttonName: 'ux_go_to_gdrivebkup',
    visible: true,
    newBadge: true,
    disable: 'ff_disableGDriveBackup',
  },
  {
    position: 4,
    categoryName: 'Wallet',
    name: 'PrivateKey',
    text: 'profiles.user_profile_menu.export_private_key',
    route: '/wallets/export-private-key',
    type: 'link',
    visible: true,
    newBadge: false,
  },
  {
    position: 5,
    categoryName: 'Wallet',
    name: 'RemoveWallet',
    text: 'profiles.user_profile_menu.remove_wallet',
    route: '/wallets/remove',
    type: 'link',
    buttonName: 'ux_go_to_eliminate_wallet',
    visible: true,
    newBadge: false,
  },
];
