export const LINKS = {
  generalHelp: 'https://www.info.xcapit.com/',
  apiKeyTelegramSupport: 'https://bit.ly/XcapitAPISupportT',
  apiKeyWhatsappSupport: 'https://bit.ly/XcapitAPISupportW',
  kriptonSupport: 'https://kriptonmarket.com/terms-and-conditions',
  binance: 'https://www.binance.com/',
  infoPaxful: 'https://www.notion.so/growthxcapit/Tutorial-Paxful-7a2de9251ef14e4daf0fbccf2a14c163',
  twoPiTermsAndConditions: 'https://docs.2pi.network/resources/terms-and-conditions',
  moonpayTransactionHistory: 'https://buy.moonpay.com/trade_history',
  xcapitTermsAndConditions: 'https://www.xcapit.com/terminos-y-condiciones',
  xcapitPrivacyPolicy: 'https://www.xcapit.com/politicas-de-privacidad',
  referralsTermsAndConditions: 'https://xcapit.com/financial-freedom-tyc/',
  discordCommunity: 'https://discord.gg/pHjXPvpwJG',
  oneInchToS: 'https://docs.1inch.io/docs/aggregation-protocol/api/legal/',
  twoPiPage: 'https://dashboard.2pi.network/',
  kriptonPage: 'https://kriptonmarket.com',
  requireToken: 'https://docs.google.com/forms/d/e/1FAIpQLSc1dW8XVW6wIBasrymzYvdDrOkSnrKpYdyGrO6ol5NKHKLP0w/viewform',
};
