export const LICENSES = [
  {
    id: 1,
    name: 'Explorer',
    info: 'payment.licenses.infoExplorer',
    price: 'payment.licenses.free',
    type: 'free',
    state: '',
  },
  {
    id: 2,
    name: 'Advanced',
    info: 'payment.licenses.infoAdvanced',
    price: '$118',
    type: 'paid',
    state: 'payment.licenses.annual',
  },
  {
    id: 3,
    name: 'Expert',
    info: 'payment.licenses.infoExpert',
    price: '$298',
    type: 'paid',
    state: 'payment.licenses.annual',
  },
  {
    id: 5,
    name: 'Advanced',
    info: 'payment.licenses.infoAdvanced',
    price: '$9,99',
    type: 'paid',
    state: 'payment.licenses.monthly',
  },
  {
    id: 6,
    name: 'Expert',
    info: 'payment.licenses.infoExpert',
    price: '$24,99',
    type: 'paid',
    state: 'payment.licenses.monthly',
  },
  {
    id: 4,
    name: 'Premium',
    info: 'payment.licenses.infoPremium',
    type: 'premium',
    state: '',
  },
];
