export const LICENSES = [
  {
    id: 1,
    name: 'Explorer',
    info: 'Puedes invertir hasta USD$300',
    price: 'GRATIS',
    type: 'free',
    state: '',
  },
  {
    id: 2,
    name: 'Advanced',
    info: 'Invierte hasta USD$10.000',
    price: '$118',
    type: 'paid',
    state: 'anual',
  },
  {
    id: 3,
    name: 'Expert',
    info: 'Invierte hasta USD$50.000',
    price: '$298',
    type: 'paid',
    state: 'anual',
  },
  {
    id: 6,
    name: 'Advanced',
    info: 'Invierte hasta USD$10.000',
    price: '$9,99',
    type: 'paid',
    state: 'mensual',
  },
  {
    id: 7,
    name: 'Expert',
    info: 'Invierte hasta USD$50.000',
    price: '$24,99',
    type: 'paid',
    state: 'mensual',
  },
  {
    id: 4,
    name: 'Premium',
    info: 'Para inversiones mayores a USD$50.000',
    type: 'premium',
    state: '',
  },
];
